### ISSUE TITLE
Error when vertically remapping the data

### ISSUE THREAD

**Issue by dongxthu** [E3SM-Project/HICCUP#44]
Hi HICCUP Team,

I would like to use HICCUP to create a new initial data using ERA5 and NOAA SST. However, I met an error when vertically remapping the data.
Attached are error report and my code, I would greatly appreciate it if you could help me solve that!

Best regards,
Dong

[error.txt](https://github.com/user-attachments/files/17964447/error.txt)
[create_EAM_IC_from_ERA5-NOAA.txt](https://github.com/user-attachments/files/17964450/create_EAM_IC_from_ERA5-NOAA.txt)

**Comment by dongxthu** [comment]
Hi Team,

I met a new question when performing state adjustments:


Removing super saturated data points...
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/uufs/chpc.utah.edu/common/home/zpu-group29/dxu/HICCUP/user_scripts/data_20220101/tmp_atm_data.ne30np4pg2.L80.Q.20241202.025752.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/zpu-group29/dxu/HICCUP/user_scripts/data_20220101/create_EAM_IC_from_ERA5-NOAA.py", line 131, in <module>
    hiccup_data.atmos_state_adjustment_multifile(file_dict=file_dict)
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/hiccup/hiccup_data_class.py", line 968, in atmos_state_adjustment_multifile
    ds_data[var_dict['Q']].to_netcdf(file_dict[var_dict['Q']],format=hiccup_atm_nc_format,mode='a')
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/core/dataarray.py", line 2839, in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/core/dataset.py", line 1902, in to_netcdf
    return to_netcdf(
           ^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/api.py", line 1055, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 379, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 327, in __init__
    self.format = self.ds.data_model
                  ^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 388, in ds
    return self._acquire()
           ^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 382, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/uufs/chpc.utah.edu/sys/installdir/r8/python/3.11.3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u6063131/.local/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 2521, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2158, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: '/uufs/chpc.utah.edu/common/home/zpu-group29/dxu/HICCUP/user_scripts/data_20220101/tmp_atm_data.ne30np4pg2.L80.Q.20241202.025752.nc'



Thank you!!

Dong
